image: python:3.5
stages:
    - test
    - package
cache:
    paths:
        - cache/
    key: $CI_BUILD_REF_NAME
before_script:
    - export PIP_CACHE_DIR=$PWD/cache/pip/; export PRE_COMMIT_HOME=$PWD/cache/precommit/

test:
    stage: test
    script:
        - pip install -U pip
        - pip install -e .[dev]
        - pytest

style:
    stage: test
    script:
        - pip install pre-commit -e .[dev]
        - pre-commit run --all-files
    except:
        - tags

package:
    stage: package
    script:
        - pip install wheel
        - python setup.py bdist_wheel
        - mv dist/*.whl .
    artifacts:
        paths:
            - "*.whl"
