-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: 5bf6c09bfa1297d3692cadd621ef95f1284e33c0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: debug-statements
        language_version: python3.5
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: autopep8-wrapper
        language_version: python3.5
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    sha: v1.0.1
    hooks:
    -   id: forbid-crlf
        exclude: \.csv$
    -   id: forbid-tabs
        exclude: Makefile|\.bat$
-   repo: git://github.com/FalconSocial/pre-commit-python-sorter
    sha: b57843b0b874df1d16eb0bef00b868792cb245c2
    hooks:
    -   id: python-import-sorter
        language_version: python3.5
-   repo: git://github.com/guykisel/prospector-mirror
    sha: e0bfe1f71f9b6c81c5b8b8ffece9d89b0142c4b8
    hooks:
    -   id: prospector
        language_version: python3.5
